# Generated by Django 5.0.5 on 2024-05-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('uploader', models.CharField(max_length=50)),
                ('address', models.URLField()),
                ('tags', models.TextField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
