# Generated by Django 5.0.5 on 2024-05-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
