# Generated by Django 5.0.5 on 2024-05-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_pdf_address_alter_pdf_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='address',
            field=models.URLField(),
        ),
    ]
